# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97de94523d39b99eb8d43fdd1481c7bd3d2d540fb0fd05c15728f3dcd16b4a43844f7bdd81952c62640d044d9b54ba1c9f08709baca0f1f67d025c4fe5cf239d

test:
  secret_key_base: 43853d70362138b847c4de7f91237b0fe6e3a16b6b1861eff1d4776b44549457953fd5bc92fc6ed5b7fb741954c7e0065f63b623fba870f22ffa8034081cd7e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
